### ISSUE TITLE
kubetest

### ISSUE THREAD

**Issue by estahn** [cloud66-oss/copper#11]
I came across copper via Kubernetes SIG Apps. What is the differentiator to [kubetest](https://github.com/garethr/kubetest)?

**Comment by khash** [comment]
Hi @estahn 

Kubetest is very similar to Copper. The biggest difference is the user experience as Kubetest needs the tests to be written in python and Copper uses a simple DSL instead.

This makes Copper easier to start with for many non-python developers, but more importantly makes it safe to run on hosted environments where potentially unsafe python code can be used as test.

I would use Kubetest to write unit tests for Kuberentes internally, and Copper to let my Ops guys built best practices and compliance rules that are automatically run against Kubernetes configuration files my Devs write. 

We use Copper in [Cloud 66 Skycap](https://cloud66.com/containers/skycap) exactly for that!
