### ISSUE TITLE
Documentation off

### ISSUE THREAD

**Issue by Code0x58** [cloud66-oss/copper#14]
Under the [jsonpath](https://copper.sh/docs/copper-dsl/#jsonpath-syntax) part, it says:
```
fetch("$.spec.spec.containers[?(@.name == 'mysql')]") // will return ["index.docker.io/library/ubuntu:latest"]
```
But I think it should be something like (not sure if it's missing a dot):
```
fetch("$.spec.spec.containers[?(@.name == 'mysql')].image") // will return ["quay.io/mysql:2.3.0"]
```

**Comment by khash** [comment]
Thank you @Code0x58 

This is now fixed!
