### ISSUE TITLE
gem ships binaries that conflict

### ISSUE THREAD

**Issue by krainboltgreene** [cloud66-oss/copper#15]
```
c66-copper's executable "console" conflicts with countries
Overwrite the executable? [yN]  y
c66-copper's executable "setup" conflicts with paper_trail-background
Overwrite the executable? [yN]  y
```

**Comment by khash** [comment]
@krainboltgreene how are you installing it? Have you tried installing it on a separate gemset?

**Comment by khash** [comment]
Hi @krainboltgreene  

A new version of Copper was released today (the old version is still available under the `ruby` branch). This version is a rewrite of Copper, replacing the custom DSL with Javascript. 

This version is in beta and is the one we will be actively developing going forward.
