### ISSUE TITLE
reading yml files from directory

### ISSUE THREAD

**Issue by srjayep** [cloud66-oss/copper#8]
Is there a way to read bunch of yaml files from directory instead just a file to apply the rule. I currently have yml files stored in "files" directory and --file option isn't reading all the files. 

copper check --rules myrule.cop --file files/*.yml

tried 
copper check --rules myrule.cop --dir files/*.yml , but no worky. 

ERROR: "copper check" was called with arguments ["--dir", "files/elastic_scc.yml", "files/test-admin.yml"]
Usage: "copper check"

**Comment by khash** [comment]
@srjayep currently Copper doesn't support multiple file checks (it does support multiple yamls in a single file separated by `---` however). 

To run Copper for multiple files in a folder you can try something like this:

```
for file in /dir/*
do
  copper [option] --file "$file" 
done
```
